name: 'Validation'
on: 
  push:
    branches-ignore:
      - wip/**
  pull_request:

jobs:
  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Deps
      run: npm ci
    - name: Typecheck
      run: npm run type-check

  test-unit:
    name: Unit Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Deps
      run: npm ci
    - name: Run Tests
      run: npx vitest

  test-playwright:
    name: Playwright Tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
    
    steps:
    - uses: actions/checkout@v4
    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install Deps
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Tests
      run: npx playwright test